# Exercise Sheet 04: Knowledge Tracing

**Introduction to Data Mining WS23/24**  
**Bielefeld University**  
**Alina Deriyeva, Benjamin Paaßen**  
**Exercise Sheet Publication Date: 2023-12-04**  
**Exercise Sheet Submission Deadline: 2023-12-15, noon (i.e. 12:00), via **moodle** (please do not use e-mail submissions anymore).

**NOTE** The use of language models/AI tools is permitted IF you notify us of the use (just indicate it in the respective task) and are still able to understand and present your results. We also appreciate it if you link to a chatlog of the interaction with the language model/AI tool so that we can understand better how students tend to use these tools.

**PLEASE INDICATE ALL AUTHORS OF THE SUBMISSION IN THIS FIELD**

### Preamble: Data set

Consider the data set in `sheet04_data.csv`. This data set contains the exercise results for a population of fictional students and two skills.

Each row corresponds to one attempt of one student on an exercise. The first column indicates the student index $i$, the second column the time $t$, the third column the exercise index $j$, the fourth whether this exercise needs the first skill (0 if no, 1 if yes), the fifth column whether this exercise needs the second skill (0 if no, 1 if yes), and the sixth column the outcome of the attempt: 0 for a failure, 1 for a success.

The following code loads the raw data and prints it.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

X = np.loadtxt('sheet04_data.csv', skiprows = 1, delimiter = '\t', dtype=int)
print(X)

[[ 0  0  1  1  0  0]
 [ 0  1  1  1  0  0]
 [ 0  2  1  1  0  0]
 [ 0  3  2  0  1  0]
 [ 0  4  1  1  0  0]
 [ 0  5  4  1  1  1]
 [ 0  6  3  0  1  0]
 [ 0  7  4  1  1  1]
 [ 0  8  1  1  0  1]
 [ 0  9  4  1  1  1]
 [ 0 10  2  0  1  1]
 [ 1  0  4  1  1  1]
 [ 1  1  2  0  1  0]
 [ 1  2  3  0  1  1]
 [ 1  3  2  0  1  1]
 [ 1  4  2  0  1  1]
 [ 1  5  4  1  1  1]
 [ 1  6  3  0  1  1]
 [ 1  7  2  0  1  1]
 [ 1  8  0  1  0  1]
 [ 2  0  5  1  1  0]
 [ 2  1  2  0  1  0]
 [ 2  2  3  0  1  1]
 [ 2  3  0  1  0  1]
 [ 2  4  3  0  1  0]
 [ 2  5  4  1  1  1]
 [ 2  6  4  1  1  1]
 [ 2  7  0  1  0  1]
 [ 2  8  0  1  0  1]
 [ 2  9  1  1  0  1]
 [ 3  0  1  1  0  0]
 [ 3  1  3  0  1  0]
 [ 3  2  5  1  1  0]
 [ 3  3  3  0  1  0]
 [ 3  4  5  1  1  1]
 [ 3  5  3  0  1  0]
 [ 3  6  3  0  1  0]
 [ 3  7  3  0  1  1]
 [ 3  8  4  1  1  1]
 [ 3  9  0  1  0  1]
 [ 3 10  1  1  0  1]
 [ 4  0  4  1  1  0]
 [ 4  1  2  0  1  0]
 [ 4  2  0  1  0  0]
 [ 4  3  4  1  1  0]
 [ 4  4  0  1  0  1]
 [ 4  5  2  0  1  1]
 [ 4  6  0  1

In the remainder of this sheet, we will apply three different knowledge tracing methods to this data:
* Performance Factors Analysis
* Bayesian Knowledge Tracing
* Deep Knowledge Tracing

### Task 04.01

Just by considering the data set itself, which of the three knowledge tracing methods might fit best? Provide a reasoning for your answer.

**ANSWER:**

### Task 04.02

Let's assume that some local government wants to use a deep knowledge tracing model on this data to estimate the skill development of students to make funding decisions. In particular, school funding should be allocated to the schools that achieve a fastest skill development of students according to the model (conversely, funding should be reduced for schools that achieve less fast skill development).

Which problems do you see with this kind of approach? Please list at least two and explain them.

**ANSWER:**

## Performance Factors analysis


Recall the form of a performance factors analysis model: The logit-probability that student $i$ achieves a success at time step $t$, given all their previous successes and failures, is modelled as

\begin{equation}
\sum_{k \in \mathcal{K}_{i, t}} \gamma_k \cdot s_{i, k, t} + \rho_k \cdot f_{i, k, t} + \beta_k
\end{equation}

where $\mathcal{K}_{i, t}$ is the set of skills needed for the exercise student $i$ attempts at time step $t$, where $s_{i, k, t}$ is the number of past successes of student $i$ on skill $k$ before time step $t$, where $f_{i, k, t}$ is the number of past failures of student $i$ on skill $k$ before time step $t$, and where $\gamma_k$, $\rho_k$, and $\beta_k$ are the parameters of the model.

Note that this is, essentially, a logistic regression model, where $s_{i, k, t}$ and $f_{i, k, t}$ are the features and $x_{i, t}$ is the target to be predicted.


### Task 04.03

Convert the data set into a feature matrix `Xlogreg` for a logistic [sklearn.linear_model.LogisticRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) model, where each row corresponds to one attempt of one student $i$ on an exercise (just as in the raw data) and where the columns are $s_{i, 1, t}$, $f_{i, 1, t}$, 1, $s_{i, 2, t}$, $f_{i, 2, t}$, and 1 again, meaning the past successes and the past failures for the first and the second skill for student $i$ at time $t$.

HOWEVER make sure to set the first three columns to zero in every row where the exercise that student $i$ attempts at time $t$ does not involve the first skill and the last three columns to zero in every row where the exercise does not involve the second skill.

**HINT:** Look again at the lecture slides for an example of this process. While this task is not hard to program, per se, the devil is in the details.

### Task 04.04

Use the matrix `Xlogreg` from Task 04.03 and the last column of `X` (as targets) to train an [sklearn.linear_model.LogisticRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) model with `penalty = 'l2'`, `fit_intercept = False`, and `C = 1.0`.

Report the accuracy of the model by printing the output of the `score` function of the model.

### Task 04.05

Print the trained parameters of the model in the following format:

```
gamma_1 = %g
rho_1   = %g
beta_1  = %g
gamma_2 = %g
rho_2   = %g
beta_2  = %g
```

Given these parameters, compute the amount of first skill for a student with 3 past successes and 1 past failure and print it.

### Task 04.06

For each student in the data set, provide a plot with time on the x axis and the predicted success probability of the performance factors analysis model on the y axis.

### Task 04.07

In the previous task, you probably noticed that the predicted success probability of the performance factors analysis model sometimes drops for later timesteps. Explain this finding.

**ANSWER:** 

### Task 04.08 (Bonus Task)

Extend the performance factors analysis model with exercise difficulty parameters and fit it to the data. Print the accuracy and the parameters. How did this change influence the accuracy compared to the model in Task 04.04?

**ANSWER:** 

## Bayesian Knowledge Tracing

A Bayesian Knowledge Tracing Model is a two-state Hidden Markov Model (either a student mastered a skill at time $t$ or they did not), where we denote the random variable for the state of student $i$ at time $t$ as $Z_{i, t}$ and the random variable for the result (pass/fail) of student $i$ at time $t$ as $X_{i, t}$. The parameters of the model are:

\begin{align*}
p_{Z_{i, 1}}(1) &= p_\mathrm{start},\\
p_{X_{i, t}|Z_{i, t}}(0|1) &= p_\mathrm{slip}, \\
p_{X_{i, t}|Z_{i, t}}(1|0) &= p_\mathrm{guess}, \\
p_{Z_{i, t}|Z_{i, t-1}}(1|1) &= 1, &\text{ and} \\
p_{Z_{i, t}|Z_{i, t-1}}(1|0) &= p_\mathrm{trans}
\end{align*}

Given a series of past results $x_{i, 1}, \ldots, x_{i, t}$ for student $i$, we denote:

\begin{align}
p_{i, t+1} &= p_{Z_{i, t+1}|X_{i, t}, \ldots, X_{i, 1}}(1|x_{i, t}, \ldots, x_{i, 1}) & \text{ and} \\
q_{i, t}   &= p_{Z_{i, t}|X_{i, t}, \ldots, X_{i, 1}}(1|x_{i, t}, \ldots, x_{i, 1})
\end{align}

With these two short-hand notations, we obtain the following equations (refer to the lecture slides for the derivation):
\begin{align}
p_{i, t+1} &= q_{i, t} + p_\mathrm{trans} \cdot (1 - q_{i, t}) \\
q_{i, t}   &=
\begin{cases}
\frac{(1-p_\mathrm{slip}) \cdot p_{i, t}}{(1-p_\mathrm{slip}) \cdot p_{i, t} + p_\mathrm{guess} \cdot (1 - p_{i, t})} & \text{if } x_{i, t} = 1 \\
\frac{p_\mathrm{slip} \cdot p_{i, t}}{p_\mathrm{slip} \cdot p_{i, t} + (1-p_\mathrm{guess}) \cdot (1 - p_{i, t})} & \text{if } x_{i, t} = 0
\end{cases}
\end{align}

### Task 04.09

Let's assume we have a series of results $x_{i, 1}, \ldots, x_{i, t}$ for student $i$ with the last entry being $x_{i, t} = 1$.

Further, let's denote the joint probability $p_{Z_{i, t}, X_{i, t}, \ldots, X_{i, 1}}(z, x_{i, t}, \ldots, x_{i, 1})$ as $\alpha_{i, t}(z)$.

Show, that the following equality holds:
\begin{equation*}
\alpha_{i, t}(1) = (1 - p_\mathrm{slip}) \cdot \Big[p_\mathrm{trans} \cdot \alpha_{i, t-1}(0) + \alpha_{i, t-1}(1)\Big]
\end{equation*}

**HINT**: Recall that, in a BKT model, the latent space $Z_{i, t}$ of student $i$ at time $t$ is conditionally independent of all past observations given $Z_{i, t-1}$ and $X_{i, t}$ is conditionally independent from past observations given $Z_{i, t}$.

Other than these bits of information, you 'only' need to smartly apply the definition of conditional probabilities and the law of total probability for this task. 

**ANSWER:**

### Task 04.10

Given the equations above, write a Python function that takes an array $x_{i, 1}, \ldots, x_{i, t}$ of student results (pass/fail) for one skill and the parameters $p_\mathrm{start}$, $p_\mathrm{slip}$, $p_\mathrm{guess}$, and $p_\mathrm{trans}$ as input and returns an array of probability $p_{i, 1+1}, \ldots, p_{i, t+1}$ as output.

### Task 04.11

For this task, use the parameter settings $p_\mathrm{start} = 0.1$, $p_\mathrm{slip} = 0.1$, $p_\mathrm{guess} = 0.2$, and $p_\mathrm{trans} = 0.3$.

For each student and each skill, provide a plot with time step $t$ on the x axis and $p_{i, t+1}$ on the y axis, using your function from Task 04.10.

### Task 04.12

For each of the parameters, test what happens if you increase the parameter by 0.1. Report the effect on $p_{i, t+1}$.

**ANSWER FOR $p_\mathrm{start}$:** 

**ANSWER FOR $p_\mathrm{slip}$:** 

**ANSWER FOR $p_\mathrm{guess}$:** 

**ANSWER FOR $p_\mathrm{trans}$:** 

## Deep Knowledge Tracing

### Task 04.13

Generate a list `Xs_dkt` of matrices, one per student.

The matrix `Xi` for student $i$ should start with one row of zeros and each subsequent row `Xi[t+1, :]` of the matrix should correspond to one attempt of student $i$ at some exercise at time $t$. There should be two columns per exercise (twelve columns overall), where entry `Xi[t+1, j]` should be 1 if the attempt $t$ was successful and `Xi[t+1, 6 + j]` should be 1 if the attempt was a failure. The last attempt of the student should not be represented in `Xi`.

For example, if student $i$ has three attempts, one success on exercise 0, one failure on exercise 2, and a success on exercise 2, then the matrix `Xi` should be as follows:

```
Xi = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # zero row for the first attempt
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], # first attempt (success at first exercise)
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]  # second attempt (failure at third exercise)
]
```

Generate a list `Ys_dkt` of matrices, one per student, which contain the exercise indices and the results results of the student.

For example, if student $i$ has three attempts, one success on exercise 0, one failure on exercise 2, and a success on exercise 2, then `Yi` should be as follows:

```
Yi = [
    [0, 1],
    [2, 0],
    [2, 1]
]
```

In [2]:
import torch
num_exercises = 6

### Task 04.14

The following deep knowledge tracing model takes a student matrix `Xi` from Task 04.13 as input and produces a matrix `Logits` with as many rows and 6 columns, one per exercise. The entry `Logits[t, j]` is supposed to be the logit probability of student $i$ succeeding at exercise $j$ in time step $t$.

To train this model, we want to use the following scheme:

Repeat for num_epochs:
1. Pick a random student $i$.
2. Get the matrix `Xi` and the array `Yi` from Task 04.11.
3. Compute the output `Logits` for input `Xi` via the `forward` method of the DKT modul.
4. For each time step $t$, repeat:
    1. Retrieve the exercise index `j = Yi[t, 0]` and the actual result `x = Yi[t, 1]`.
    2. Use the function `torch.nn.functional.binary_crossentropy_with_logits` to compute the loss between the predicted logit probability `Logits[t, j]` and the actual outcome `x`.

Implement this scheme in the `fit` function of the model below.

In [3]:
import torch
import random

class DKT(torch.nn.Module):
    """The initialization function of a pytorch module. Here, we should set all hyperparameters
    of the model, such as the regularization strength.

    Parameters
    ----------
    num_exercises: int
        The number of exercises in the data set.
    num_neurons: int (default = 32)
        The number of neurons used in the GRU.
    C: float (default = 1000)
        The inverse of the L2 regularization strength.
    num_epochs: int (default = 1000)
        How many times we iterate over the data set.
    learning_rate: float (default = 1E-2)

    """
    def __init__(self, num_exercises, num_neurons = 32, C = 1000., num_epochs = 1000, learning_rate = 1E-2):
        super(DKT, self).__init__()
        self.num_exercises_ = num_exercises
        self.num_neurons_   = num_neurons
        self.C_             = C
        self.num_epochs_    = num_epochs
        self.learning_rate_ = learning_rate
        # initialize the network layers
        self.gru_           = torch.nn.GRU(self.num_exercises_*2, self.num_neurons_)
        self.out_           = torch.nn.Linear(self.num_neurons_, self.num_exercises_)


    """Predicts logit probabilities of success for the given input data
    
    Parameters
    ----------
    X: torch.tensor
        A feature matrix for one student, where each row represents one attempted exercise.
        The first self.num_exercises_ columns should indicate whether a student achieved
        a success at exercise j in this timestep, the latter self.num_exercises_ columns
        should indicate failures.

    Returns
    -------
    Logits: torch.tensor
        A matrix where the entry Logits[t, j] indicates the predicted logit success probability
        for the student for exercise j at time t.

    """
    def forward(self, X):
        H, _ = self.gru_(X)
        return self.out_(H)

    """Scores the accuracy of this model.
    
    Parameters
    ----------
    X: list
        A list of feature matrices, one per student.
    Y: list
        A list of target matrices, one per student.

    Returns
    -------
    acc: float
        An accuracy value.
    
    """
    def score(self, X, Y):
        num_attempts  = 0
        num_successes = 0
        for i in range(len(X)):
            Logits = self.forward(X[i])
            for t in range(Y[i].shape[0]):
                num_attempts += 1
                j = int(Y[i][t, 0])
                if Y[i][t, 1] > 0.5 and Logits[t, j] > 0:
                    num_successes += 1
                elif Y[i][t, 1] < 0.5 and Logits[t, j] <= 0:
                    num_successes += 1
        return num_successes / num_attempts

    """Fits this model to the given data matrix.

    Parameters
    ----------
    X: list
        A list of feature matrices, one per student.
    Y: list
        A list of target matrices, one per student.

    """
    def fit(self, X, Y):
        raise ValueError('This needs to be implemented!')

### Task 04.15

Train the model on the data using your `fit` function from Task 04.14 and report the accuracy using the `score` function.